version: '3'
services:
  postgres:
    image: postgres:13
    container_name: sequalize-auth
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
  posgres_test:
    image: postgres:13
    container_name: sequalize-auth-test
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
    ports:
      - '5433:5432'
